name: Update Release Sizes

on:
  release:
    types: [published]

jobs:
  generate-sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate sizes JSON
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          REPO: ${{ github.repository }}
        run: |
          mkdir -p docs
          
          # Fetch release data directly in this step
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/$RELEASE_TAG" \
            | jq --arg ver "$RELEASE_TAG" '
              [ .assets[]
                | select(.name | endswith(".exe"))
                | { name: .name, size: .size, url: .browser_download_url }
              ]
              | {
                  version: $ver,
                  min_size: (min_by(.size) | .size),
                  max_size: (max_by(.size) | .size),
                  files: .
                }' \
            > docs/sizes.json
      
      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/sizes.json
          git commit -m "Update sizes.json for ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push
